/* Generated By:JJTree: Do not edit this line. ASTBinaryOpExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.detwiler.owltools.owlpaths;

public
class ASTBinaryOpExpr extends org.detwiler.owltools.owlpaths.util.PathNode {
  public ASTBinaryOpExpr(int id) {
    super(id);
  }

  public ASTBinaryOpExpr(PathExpression p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PathExpressionVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f3f1e0b58ba038e43f986895c9aedfd2 (do not edit this line) */
