/* Generated By:JJTree: Do not edit this line. ASTPropertyExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.detwiler.owltools.owlpaths;

public
class ASTPropertyExpr extends org.detwiler.owltools.owlpaths.util.PathNode {
  public ASTPropertyExpr(int id) {
    super(id);
  }

  public ASTPropertyExpr(PathExpression p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PathExpressionVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e5a416df7f8c88f193e668fc9300f01a (do not edit this line) */
