/* Generated By:JJTree: Do not edit this line. ASTUnaryOpExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.detwiler.owltools.owlpaths;

public
class ASTUnaryOpExpr extends org.detwiler.owltools.owlpaths.util.PathNode {
  public ASTUnaryOpExpr(int id) {
    super(id);
  }

  public ASTUnaryOpExpr(PathExpression p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PathExpressionVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=24c5c1ec9f17470f347f82ff8ef5fa4b (do not edit this line) */
