/* Generated By:JJTree&JavaCC: Do not edit this line. PathExpressionConstants.java */
package org.detwiler.owltools.owlpaths;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PathExpressionConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LGROUP = 5;
  /** RegularExpression Id. */
  int RGROUP = 6;
  /** RegularExpression Id. */
  int LANGLE = 7;
  /** RegularExpression Id. */
  int RANGLE = 8;
  /** RegularExpression Id. */
  int COLON = 9;
  /** RegularExpression Id. */
  int CONCAT = 10;
  /** RegularExpression Id. */
  int ALT = 11;
  /** RegularExpression Id. */
  int STAR = 12;
  /** RegularExpression Id. */
  int PLUS = 13;
  /** RegularExpression Id. */
  int OPT = 14;
  /** RegularExpression Id. */
  int SUP_FILTER = 15;
  /** RegularExpression Id. */
  int INV_FILTER = 16;
  /** RegularExpression Id. */
  int URI_CHAR = 17;
  /** RegularExpression Id. */
  int URI_SPECIAL_CHAR = 18;
  /** RegularExpression Id. */
  int PREF_URI_CHAR = 19;
  /** RegularExpression Id. */
  int FULL_URI = 20;
  /** RegularExpression Id. */
  int PREFIX_URI = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\">\"",
    "\":\"",
    "\"/\"",
    "\"|\"",
    "\"*\"",
    "\"+\"",
    "\"?\"",
    "<SUP_FILTER>",
    "<INV_FILTER>",
    "<URI_CHAR>",
    "<URI_SPECIAL_CHAR>",
    "<PREF_URI_CHAR>",
    "<FULL_URI>",
    "<PREFIX_URI>",
  };

}
