/* Generated By:JavaCC: Do not edit this line. PathExpressionVisitor.java Version 7.0.10 */
package org.detwiler.owltools.owlpaths;

public interface PathExpressionVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTBinaryOpExpr node, Object data);
  public Object visit(ASTPropertyExpr node, Object data);
  public Object visit(ASTFullIRIExpr node, Object data);
  public Object visit(ASTPrefixIRIExpr node, Object data);
  public Object visit(ASTUnaryOpExpr node, Object data);
}
/* JavaCC - OriginalChecksum=fcaa5e33c7679b253c510385039a61f2 (do not edit this line) */
