/* Generated By:JavaCC: Do not edit this line. PathExpressionTreeConstants.java Version 7.0.10 */
package org.detwiler.owltools.owlpaths;

public interface PathExpressionTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTBINARYOPEXPR = 2;
  public int JJTPROPERTYEXPR = 3;
  public int JJTFULLIRIEXPR = 4;
  public int JJTPREFIXIRIEXPR = 5;
  public int JJTUNARYOPEXPR = 6;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "BinaryOpExpr",
    "PropertyExpr",
    "FullIRIExpr",
    "PrefixIRIExpr",
    "UnaryOpExpr",
  };
}
/* JavaCC - OriginalChecksum=ec8b93c82c3132695ef28aea15cacf1a (do not edit this line) */
